services:
  royal-db:
    container_name: royal-db
    image: ${POSTGRES_IMAGE:-postgres:17.4-bookworm}
    env_file:
      - /home/ubuntu/royal-foam/.env.prod.db
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/backups:/backups
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      royal-network:
        aliases:
          - database

  royal-backend:
    container_name: royal-backend
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    env_file:
      - .env.prod
    depends_on:
      royal-db:
        condition: service_healthy
    volumes:
      - media:/home/app/backend/media
      - static:/home/app/backend/static
    restart: unless-stopped
    networks:
      - royal-network

  royal-nginx:
    container_name: royal-nginx
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - media:/var/www/media
      - static:/var/www/static
      - ./apps/nginx:/etc/nginx/conf.d:ro
      - ./certbot/conf:/etc/nginx/ssl:ro
      - ./certbot/www:/var/www/certbot
    depends_on:
      royal-backend:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - royal-network

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: /bin/sh -c "trap exit TERM; while :; do sleep 12h && certbot renew --webroot --webroot-path=/var/www/certbot && nginx -s reload; done"
    networks:
      - royal-network
    depends_on:
      - royal-nginx

volumes:
  db-data:
  media:
  static:

networks:
  royal-network:
    driver: bridge
