# Generated by Django 5.0.4 on 2024-06-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField()),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField()),
                ("message", models.TextField()),
                ("agree", models.BooleanField()),
            ],
            options={
                "verbose_name": "Contact Us",
                "verbose_name_plural": " Contact Us",
            },
        ),
        migrations.CreateModel(
            name="Subscribe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
            ],
            options={
                "verbose_name": "Subscribe",
                "verbose_name_plural": "Subscribe",
            },
        ),
    ]
