# Generated by Django 5.0.7 on 2024-08-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='full_name',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='subject',
            field=models.CharField(max_length=225),
        ),
    ]
