# Generated by Django 5.0.4 on 2024-05-17 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Catagory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, null=True)),
                ("slug", models.SlugField(null=True)),
                ("image", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Catagory",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="post",
            name="categories",
        ),
        migrations.RemoveField(
            model_name="post",
            name="author",
        ),
        migrations.RemoveField(
            model_name="postview",
            name="post",
        ),
        migrations.RemoveField(
            model_name="postview",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={},
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="content",
            new_name="body",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="created_on",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="author",
        ),
        migrations.AddField(
            model_name="comment",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, null=True)),
                ("detail", models.TextField(max_length=2000, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/media"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "active"), ("pending", "pending")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("featured", models.BooleanField(default=False)),
                ("visit_count", models.IntegerField(default=0)),
                ("visible", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "catagories",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="blog.catagory",
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, to="blog.tag")),
            ],
            options={
                "verbose_name_plural": "Blog",
            },
        ),
        migrations.AlterField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="blog.blog",
            ),
        ),
        migrations.CreateModel(
            name="Reply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, null=True)),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reply",
                        to="blog.comment",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="PostView",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
    ]
