# Generated by Django 5.0.4 on 2024-05-18 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_catagory_tag_remove_post_categories_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Catagory",
            new_name="Category",
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Category"},
        ),
    ]
