# Generated by Django 5.0.4 on 2024-06-02 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_category_options_alter_reply_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="reply",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ["pk"]},
        ),
    ]
