# Generated by Django 5.0.4 on 2024-06-02 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_alter_comment_options_alter_reply_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="image",
        ),
    ]
