# Generated by Django 5.0.4 on 2024-06-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_remove_category_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(
                blank=True, max_length=500, null=True, verbose_name="Description"
            ),
        ),
    ]
