# Generated by Django 5.0.4 on 2024-06-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_post_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="blog-media"),
        ),
    ]
