# Generated by Django 5.0.4 on 2024-06-02 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_alter_post_video"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="video",
            new_name="media",
        ),
    ]
