# Generated by Django 5.0.4 on 2024-05-25 00:47

import django.db.models.deletion
from django.db import migrations, models

import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                (
                    "slug",
                    models.SlugField(allow_unicode=True, max_length=255, unique=True),
                ),
                (
                    "background_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="category-backgrounds"
                    ),
                ),
                ("background_image_alt", models.CharField(blank=True, max_length=128)),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="products.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                (
                    "slug",
                    models.SlugField(allow_unicode=True, max_length=255, unique=True),
                ),
                (
                    "description",
                    models.TextField(blank=True, max_length=250, null=True),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            (
                                "R-Esteem",
                                [
                                    ("RPS/01", "6.25x6x10"),
                                    ("RPS/02", "6.25x7x10"),
                                    ("RPS/03", "6x6.6x10"),
                                ],
                            ),
                            (
                                "R-Infinty",
                                [
                                    ("RSI/01", "6.25x6x12"),
                                    ("RSI/02", "6.25x7x12"),
                                    ("RSI/03", "6x6.6x12"),
                                ],
                            ),
                            (
                                "R-Elite",
                                [
                                    ("REL/0l", "6.25x3.5x8"),
                                    ("REL/02", "6.25x4.5x8"),
                                    ("REL/03", "6.25x6x8"),
                                    ("REL/04", "6.25x7x8"),
                                    ("REL/05", "6.25x4.5x10"),
                                    ("REL/06", "6.25x6x10"),
                                    ("REL/07", "6.25x7x10"),
                                    ("REL/08", "6.26x4.5x12"),
                                    ("REL/09", "6.25x6x12"),
                                    ("REL/10", "6.25x7x12"),
                                ],
                            ),
                            ("unknown", "Unknown"),
                        ],
                        default="R-Esteem",
                        max_length=250,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("rating", models.FloatField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="products.category",
                    ),
                ),
            ],
            options={
                "ordering": ("slug",),
                "permissions": (("Manage products.", "Can manage products"),),
            },
        ),
        migrations.CreateModel(
            name="ProductMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="media")),
                ("alt", models.CharField(blank=True, max_length=128)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("IMAGE", "An uploaded image or an URL to an image"),
                            ("VIDEO", "A URL to an external video"),
                        ],
                        default="IMAGE",
                        max_length=32,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ("pk",),
            },
        ),
        migrations.CreateModel(
            name="Thumbnail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="thumbnails")),
                (
                    "size",
                    models.PositiveIntegerField(
                        validators=[products.models.validate_thumbnail_size]
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("original", "Original"),
                            ("avif", "AVIF"),
                            ("webp", "WebP"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thumbnails",
                        to="products.category",
                    ),
                ),
                (
                    "product_media",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thumbnails",
                        to="products.productmedia",
                    ),
                ),
            ],
        ),
    ]
