# Generated by Django 5.0.4 on 2024-06-16 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Category",
            new_name="ProductCategory",
        ),
        migrations.AlterModelOptions(
            name="productcategory",
            options={"ordering": ("pk",), "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="thumbnail",
            options={"ordering": ("pk",)},
        ),
        migrations.RenameField(
            model_name="product",
            old_name="category",
            new_name="product_category",
        ),
        migrations.RenameField(
            model_name="thumbnail",
            old_name="category",
            new_name="product_category",
        ),
        migrations.AlterField(
            model_name="productmedia",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="product-images"),
        ),
    ]
